import { jsPDF } from "jspdf";

export type PaymentSlipData = {
  applicationId: string;
  orderId: string;
  serviceName: string;
  status: "paid" | "pending";
  currency: string;
  total: number;
  paymentReference?: string;
  paidAt?: string;
};

export function downloadPaymentSlip(data: PaymentSlipData) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 40;

  const statusText = data.status === "paid" ? "Paid" : "Pending payment";
  const referenceText =
    data.status === "paid" ? (data.paymentReference || data.orderId) : "Awaiting payment";
  const paymentDate =
    data.status === "paid" && data.paidAt
      ? new Date(data.paidAt).toLocaleDateString()
      : new Date().toLocaleDateString();

  doc.setFillColor(248, 245, 252);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setFillColor(98, 73, 158);
  doc.roundedRect(margin, 32, 30, 30, 8, 8, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("A", margin + 11, 55);

  doc.setTextColor(30, 24, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.text("Audvertax", margin + 78, 55);

  doc.setFontSize(12);
  doc.setTextColor(104, 96, 120);
  doc.text("Payment Slip", margin + 78, 74);

  doc.setDrawColor(196, 188, 206);
  doc.line(margin, 96, pageWidth - margin, 96);

  doc.setFillColor(255, 255, 255);
  doc.roundedRect(margin, 116, pageWidth - margin * 2, 360, 12, 12, "F");

  doc.setTextColor(104, 96, 120);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Application ID", margin + 24, 150);
  doc.setTextColor(30, 24, 42);
  doc.setFont("helvetica", "bold");
  doc.text(data.applicationId, margin + 24, 172);

  doc.setTextColor(104, 96, 120);
  doc.setFont("helvetica", "normal");
  doc.text("Reference / Transaction ID", margin + 24, 210);
  doc.setTextColor(30, 24, 42);
  doc.setFont("helvetica", "bold");
  doc.text(referenceText, margin + 24, 232);

  doc.setTextColor(104, 96, 120);
  doc.setFont("helvetica", "normal");
  doc.text("Service", margin + 24, 270);
  doc.setTextColor(30, 24, 42);
  doc.setFont("helvetica", "bold");
  doc.text(data.serviceName, margin + 24, 292);

  doc.setTextColor(104, 96, 120);
  doc.setFont("helvetica", "normal");
  doc.text("Payment status", pageWidth - margin - 146, 150);
  doc.setFillColor(
    data.status === "paid" ? 226 : 255,
    data.status === "paid" ? 245 : 241,
    data.status === "paid" ? 234 : 214,
  );
  doc.roundedRect(pageWidth - margin - 150, 158, 118, 26, 8, 8, "F");
  doc.setTextColor(
    data.status === "paid" ? 22 : 154,
    data.status === "paid" ? 122 : 112,
    data.status === "paid" ? 74 : 24,
  );
  doc.setFont("helvetica", "bold");
  doc.text(statusText, pageWidth - margin - 130, 177);

  doc.setTextColor(104, 96, 120);
  doc.setFont("helvetica", "normal");
  doc.text("Date", pageWidth - margin - 146, 210);
  doc.setTextColor(30, 24, 42);
  doc.setFont("helvetica", "bold");
  doc.text(paymentDate, pageWidth - margin - 146, 232);

  doc.setTextColor(104, 96, 120);
  doc.setFont("helvetica", "normal");
  doc.text("Amount", margin + 24, 330);
  doc.setTextColor(30, 24, 42);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(26);
  doc.text(`${data.currency} ${data.total.toFixed(2)}`, margin + 24, 360);

  doc.setDrawColor(214, 206, 224);
  doc.line(margin + 24, 394, pageWidth - margin - 24, 394);

  doc.setTextColor(104, 96, 120);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Generated by Audvertax", margin + 24, 430);
  doc.text("This is an electronic payment record for your application.", margin + 24, 450);

  doc.setTextColor(30, 24, 42);
  doc.setFont("helvetica", "bold");
  doc.text("Office copy", pageWidth - margin - 110, 430);

  const blob = doc.output("blob");
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `audvertax-slip-${data.applicationId}.pdf`;
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
