import type { Jurisdiction } from "./domain";

export type FormationState = {
  slug: string;
  name: string;
  abbreviation: string;
  filingFee: number;
  renewalFee: number;
  renewalDue: string;
  tag: string;
  description: string;
  suitableFor: string[];
};

// State pricing is intentionally kept here so it can be updated without touching the UI.
export const formationStates: FormationState[] = [
  {
    slug: "alabama",
    name: "Alabama",
    abbreviation: "AL",
    filingFee: 200,
    renewalFee: 100,
    renewalDue: "15 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "alaska",
    name: "Alaska",
    abbreviation: "AK",
    filingFee: 250,
    renewalFee: 100,
    renewalDue: "2 January",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "arizona",
    name: "Arizona",
    abbreviation: "AZ",
    filingFee: 50,
    renewalFee: 0,
    renewalDue: "Not required",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "arkansas",
    name: "Arkansas",
    abbreviation: "AR",
    filingFee: 45,
    renewalFee: 150,
    renewalDue: "1 May",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "california",
    name: "California",
    abbreviation: "CA",
    filingFee: 70,
    renewalFee: 820,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "colorado",
    name: "Colorado",
    abbreviation: "CO",
    filingFee: 50,
    renewalFee: 25,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "connecticut",
    name: "Connecticut",
    abbreviation: "CT",
    filingFee: 120,
    renewalFee: 80,
    renewalDue: "31 March",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "delaware",
    name: "Delaware",
    abbreviation: "DE",
    filingFee: 110,
    renewalFee: 300,
    renewalDue: "1 June",
    tag: "Investor friendly",
    description:
      "A well-known jurisdiction for companies with more complex corporate or investor requirements.",
    suitableFor: [
      "Investor-focused businesses",
      "Startups",
      "Companies expecting outside investment",
    ],
  },
  {
    slug: "florida",
    name: "Florida",
    abbreviation: "FL",
    filingFee: 125,
    renewalFee: 138.75,
    renewalDue: "1 May",
    tag: "Popular operating state",
    description: "A popular operating state for businesses with a genuine Florida connection.",
    suitableFor: ["Florida-based businesses", "Local businesses", "Operating businesses"],
  },
  {
    slug: "georgia",
    name: "Georgia",
    abbreviation: "GA",
    filingFee: 100,
    renewalFee: 50,
    renewalDue: "1 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "hawaii",
    name: "Hawaii",
    abbreviation: "HI",
    filingFee: 50,
    renewalFee: 15,
    renewalDue: "Anniversary+qtr",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "idaho",
    name: "Idaho",
    abbreviation: "ID",
    filingFee: 100,
    renewalFee: 0,
    renewalDue: "Anniversay",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "illinois",
    name: "Illinois",
    abbreviation: "IL",
    filingFee: 150,
    renewalFee: 75,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "indiana",
    name: "Indiana",
    abbreviation: "IN",
    filingFee: 95,
    renewalFee: 131,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "iowa",
    name: "Iowa",
    abbreviation: "IA",
    filingFee: 50,
    renewalFee: 30,
    renewalDue: "1 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "kansas",
    name: "Kansas",
    abbreviation: "KS",
    filingFee: 165,
    renewalFee: 500,
    renewalDue: "15 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "kentucky",
    name: "Kentucky",
    abbreviation: "KY",
    filingFee: 40,
    renewalFee: 15,
    renewalDue: "30 June",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "louisiana",
    name: "Louisiana",
    abbreviation: "LA",
    filingFee: 105,
    renewalFee: 35,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "maine",
    name: "Maine",
    abbreviation: "ME",
    filingFee: 175,
    renewalFee: 85,
    renewalDue: "1 June",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "maryland",
    name: "Maryland",
    abbreviation: "MD",
    filingFee: 100,
    renewalFee: 300,
    renewalDue: "15 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "massachusetts",
    name: "Massachusetts",
    abbreviation: "MA",
    filingFee: 500,
    renewalFee: 500,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "michigan",
    name: "Michigan",
    abbreviation: "MI",
    filingFee: 50,
    renewalFee: 25,
    renewalDue: "15 Feburary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "minnesota",
    name: "Minnesota",
    abbreviation: "MN",
    filingFee: 155,
    renewalFee: 0,
    renewalDue: "31 December",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "mississippi",
    name: "Mississippi",
    abbreviation: "MS",
    filingFee: 50,
    renewalFee: 0,
    renewalDue: "1 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "missouri",
    name: "Missouri",
    abbreviation: "MO",
    filingFee: 52,
    renewalFee: 0,
    renewalDue: "Not required",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "montana",
    name: "Montana",
    abbreviation: "MT",
    filingFee: 35,
    renewalFee: 20,
    renewalDue: "15 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "nebraska",
    name: "Nebraska",
    abbreviation: "NE",
    filingFee: 100,
    renewalFee: 13,
    renewalDue: "1 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "nevada",
    name: "Nevada",
    abbreviation: "NV",
    filingFee: 425,
    renewalFee: 350,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "new-hampshire",
    name: "New Hampshire",
    abbreviation: "NH",
    filingFee: 100,
    renewalFee: 100,
    renewalDue: "1 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "new-jersey",
    name: "New Jersey",
    abbreviation: "NJ",
    filingFee: 130,
    renewalFee: 75,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "new-mexico",
    name: "New Mexico",
    abbreviation: "NM",
    filingFee: 50,
    renewalFee: 0,
    renewalDue: "Not required",
    tag: "Low ongoing cost",
    description: "An option often considered by founders prioritizing lower ongoing state costs.",
    suitableFor: ["Non-U.S. founders", "Online businesses", "Cost-conscious founders"],
  },
  {
    slug: "new-york",
    name: "New York",
    abbreviation: "NY",
    filingFee: 200,
    renewalFee: 9,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "north-carolina",
    name: "North Carolina",
    abbreviation: "NC",
    filingFee: 125,
    renewalFee: 202,
    renewalDue: "15 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "north-dakota",
    name: "North Dakota",
    abbreviation: "ND",
    filingFee: 135,
    renewalFee: 50,
    renewalDue: "15 November",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "ohio",
    name: "Ohio",
    abbreviation: "OH",
    filingFee: 99,
    renewalFee: 0,
    renewalDue: "Not required",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "oklahoma",
    name: "Oklahoma",
    abbreviation: "OK",
    filingFee: 100,
    renewalFee: 25,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "oregon",
    name: "Oregon",
    abbreviation: "OR",
    filingFee: 100,
    renewalFee: 100,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "pennsylvania",
    name: "Pennsylvania",
    abbreviation: "PA",
    filingFee: 125,
    renewalFee: 7,
    renewalDue: "30 September",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "rhode-island",
    name: "Rhode Island",
    abbreviation: "RI",
    filingFee: 150,
    renewalFee: 50,
    renewalDue: "1 May",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "south-carolina",
    name: "South Carolina",
    abbreviation: "SC",
    filingFee: 110,
    renewalFee: 0,
    renewalDue: "Not required",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "south-dakota",
    name: "South Dakota",
    abbreviation: "SD",
    filingFee: 150,
    renewalFee: 55,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "tennessee",
    name: "Tennessee",
    abbreviation: "TN",
    filingFee: 300,
    renewalFee: 300,
    renewalDue: "1 April",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "texas",
    name: "Texas",
    abbreviation: "TX",
    filingFee: 300,
    renewalFee: 0,
    renewalDue: "15 May",
    tag: "Large-market option",
    description:
      "A major U.S. operating state that may make sense when the business has a genuine Texas connection.",
    suitableFor: ["Businesses operating in Texas", "Local businesses", "Large-market operations"],
  },
  {
    slug: "utah",
    name: "Utah",
    abbreviation: "UT",
    filingFee: 76,
    renewalFee: 18,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "vermont",
    name: "Vermont",
    abbreviation: "VT",
    filingFee: 155,
    renewalFee: 45,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "virginia",
    name: "Virginia",
    abbreviation: "VA",
    filingFee: 100,
    renewalFee: 50,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "washington",
    name: "Washington",
    abbreviation: "WA",
    filingFee: 200,
    renewalFee: 60,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "west-virginia",
    name: "West Virginia",
    abbreviation: "WV",
    filingFee: 100,
    renewalFee: 25,
    renewalDue: "1 July",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "wisconsin",
    name: "Wisconsin",
    abbreviation: "WI",
    filingFee: 130,
    renewalFee: 25,
    renewalDue: "Anniversary",
    tag: "Placeholder pricing",
    description: "A U.S. state option for LLC formation.",
    suitableFor: ["U.S. businesses"],
  },
  {
    slug: "wyoming",
    name: "Wyoming",
    abbreviation: "WY",
    filingFee: 102,
    renewalFee: 60,
    renewalDue: "Anniversary",
    tag: "Non-resident favourite",
    description: "A popular choice for founders who want a relatively simple U.S. LLC structure.",
    suitableFor: ["Non-U.S. founders", "Online businesses", "Small businesses", "E-commerce"],
  },
];

export function getFormationState(slug: string): FormationState | undefined {
  return formationStates.find((state) => state.slug === slug);
}

/** Canonical commercial jurisdiction projection; FormationState remains the UI-facing compatibility type. */
export const jurisdictions: Jurisdiction[] = formationStates.map((state) => ({
  slug: state.slug,
  code: state.abbreviation,
  name: state.name,
  country: "US",
  filingFee: state.filingFee,
  renewalFee: state.renewalFee,
  renewalRules: state.renewalDue,
  description: state.description,
  suitableFor: state.suitableFor,
}));

export function getJurisdiction(slug: string): Jurisdiction | undefined {
  return jurisdictions.find((jurisdiction) => jurisdiction.slug === slug);
}
